name: ox_chat
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path: ^1.8.0
  chewie: ^1.4.0  #Player
  screen_protector: ^1.3.0
  avatar_stack: any

  ox_module_service:
    path: ../../base_framework/ox_module_service
  ox_common:
    path: ../../base_framework/ox_common
  ox_network:
    path: ../../base_framework/ox_network
  ox_theme:
    path: ../../base_framework/ox_theme
  ox_localizable:
    path: ../../base_framework/ox_localizable
  ox_cache_manager:
    path: ../../base_framework/ox_cache_manager
  ox_chat_ui:
    path: ../../business_modules/ox_chat_ui
  ox_usercenter:
    path: ../ox_usercenter


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/images/dark/
    - assets/images/light/
    - assets/locale/
    - assets/messages.json

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
